Fix libewf V2 API support
sleuthkit/sleuthkit pull request #1052
Opened 2017-12-18 18:04 UTC by h3xx

The deprecated function `libewf_handle_read_random` was removed in [libyal/libewf@54f8d8ffb67ea3808336204d5a072db358066ec5](https://github.com/libyal/libewf/commit/54f8d8ffb67ea3808336204d5a072db358066ec5), but at that
point it was just a wrapper for `libewf_handle_read_buffer_at_offset`.[1]

Solution: Replace deprecated libewf_handle_read_random call with the
recommended[2] replacement.

Also replace the method detecting the presence of the V1 API. While I was unable to get `libewf-20160608` to compile anymore, I did confirm the presence of the `LIBEWF_OPEN_READ_WRITE` in the old source[3], and its absence in the new source.

References:

1. https://github.com/libyal/libewf/commit/54f8d8ffb67ea3808336204d5a072db358066ec5#diff-b9e76700775f6f9aa3efde388cb3bba9L74
2. https://github.com/libyal/libewf/commit/54f8d8ffb67ea3808336204d5a072db358066ec5#diff-fedcd7a7973ead791242e3a6d86e1a15L802
3. https://github.com/libyal/legacy/blob/master/libewf/libewf-20140608.tar.gz

Closes #642

2017-12-18 18:49 UTC, h3xx commented
I'd love to know from @joachimmetz if there's a better way to detect the V1 API than testing for the `LIBEWF_OPEN_READ_WRITE` macro.

2017-12-19 10:48 UTC, joachimmetz commented
V2 is the the current API version https://github.com/libyal/libewf-legacy. It introduces the libewf_handle functions. 

V3 is work in progress in the experimental version https://github.com/libyal/libewf and not finished yet

2018-01-12 20:45 UTC, h3xx commented
I'm not sure how anyone would know that the project marked "legacy" is the one that's supposed to be used, and not libyal/libewf.

"Legacy" to me means that it's old, unmaintained, and you shouldn't use it if you can avoid it.

2018-01-12 23:38 UTC, joachimmetz commented
It is but probably less unmaintained han libtsk

On Jan 12, 2018 22:02, "Dan Church" <notifications@github.com> wrote:

I'm not sure how anyone would know that the project marked "legacy" is the
one that's supposed to be used, and not libyal/libewf.

"Legacy" to me means that it's old, unmaintained, and you shouldn't use it
if you can avoid it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sleuthkit/sleuthkit/pull/1052#issuecomment-357349238>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ADtWbo507skJRRYZWsGOPz43cOm6_MTNks5tJ8UtgaJpZM4RF26s>
.

2018-01-15 09:03 UTC, joachimmetz commented
Also legacy does not mean unmaintained
https://en.m.wikipedia.org/wiki/Legacy_system

On Jan 13, 2018 00:38, "Joachim Metz" <joachim.metz@gmail.com> wrote:

> It is but probably less unmaintained han libtsk
>
> On Jan 12, 2018 22:02, "Dan Church" <notifications@github.com> wrote:
>
> I'm not sure how anyone would know that the project marked "legacy" is the
> one that's supposed to be used, and not libyal/libewf.
>
> "Legacy" to me means that it's old, unmaintained, and you shouldn't use it
> if you can avoid it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sleuthkit/sleuthkit/pull/1052#issuecomment-357349238>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADtWbo507skJRRYZWsGOPz43cOm6_MTNks5tJ8UtgaJpZM4RF26s>
> .
>
>
>

2018-08-27 18:54 UTC, dndusdndus12 commented
THX @h3xx you are my hero!!

I finally build with below dependencies (in Windows10 with VS2015)
Those are VERY NEW. (at least I believed)

libewf-experimental-20171104(https://github.com/libyal/libewf/releases)
libvhdi-alpha-20170223(https://github.com/libyal/libvhdi/releases)
libvmdk-alpha-20170226(https://github.com/libyal/libvmdk/releases)

zlib-1.2.11(https://zlib.net/)
dokan(https://github.com/joachimmetz/dokan)
bzip2-1.0.5(http://gnuwin32.sourceforge.net/packages/bzip2.htm)

If you want to build in the same way then you need to configure 
"additional library directories" for ALL but not libtsk
&
"additional include directories" only for libtsk

please note that Legacy is not a good choice. trust me I failed with it.
GOOD LUCK at your build!!

2018-08-27 22:06 UTC, joachimmetz commented
@dndusdndus12 if you run into known issue with the experimental version, don't say you've not been warned. 

> please note that Legacy is not a good choice. trust me I failed with it.

Please back this up with fact. I know the code and I do not trust your claims.

2018-08-27 22:15 UTC, dndusdndus12 commented
@joachimmetz Yes. I could have a problem with that part.
But some of the links were dead and the edits I wanted to make were inevitable because of the limitations of the version.
Thank you for letting me(and to the others) know what I missed.

2018-08-28 04:26 UTC, joachimmetz commented
> But some of the links were dead and the edits I wanted to make were inevitable because of the limitations of the version.

which links, can you be specific so broken things can be fixed?

2018-08-28 05:38 UTC, joachimmetz commented
This out of scope of the original issue.

> But the zlib and gzip library homepages in these two links are incorrect.

In the future I recommend to directly reach out to the libewf project to let the maintainers know that links are outdated. I'll address the zlib link and older Dokan support is a known (and more complicated) issue: https://github.com/libyal/libewf/issues/76

> Also, BUILDING.txt in the win32 folder of TSK 4.6.2 (http://www.sleuthkit.org/sleuthkit/download.php) was not up to date. (Eg the "https://github.com/libyal/libvhdi" link on vmdk step)

I opt to file a separate issue with sleuthkit.

2024-09-06 14:11 UTC, simsong commented
@joachimmetz & @h3xx  - Is this still relevant? I'm trying to address the old PRs.

2024-09-06 14:12 UTC, simsong commented
If it's still relevant, can you bring the PR up to the current version of develop?

2024-09-06 18:08 UTC, joachimmetz commented
FYI v3 api is still under development

2024-09-06 21:56 UTC, simsong commented
So should I accept this or drop it?

2024-09-07 00:40 UTC, bcarrier commented
Some context on this. 

We've historically tried to prioritize @joachimmetz "stable" releases.  Some libraries have no "stable" release, such as libvmdk, and therefore we will link to a recent version we have done some basic sanity checks on. 

If the goal is to accept the v3 libewf line, which is labelled as "experimental", then I think TSK needs to still support people who want to stay on the stable v2. It's never been quite clear to me if people want v3 because it's simply the most recent or if it has features (such as ex01) that are required for them.

We've never done any analysis to understand if the v3 API version of libewf has any regressions on E01 from v2. Joachim is very thorough, so I'd expect there are none. But, I also trust his labelling of these as "experimental".  

FYI: On the Windows side, there is a bunch of work around NuGet packages and such that would also need to be updated to ensure it still compiles if the default is changed to v3.

2024-09-07 00:45 UTC, simsong commented
@bcarrier  — thank you for the context. I'm in complete agreement on your desire to stay compatible with v2 libewf.  I personally think that we should detect v2 or v3 and work with either.

However, this specific PR only changes 3 lines of code:

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/ec6424dd-bd06-4092-b153-aa78b2264875">

The question is — are these APIs supported in the legacy version of libewf that we typically use?

The GitHub actions that I've been developing do not yet have proper code coverage — I'm getting there, but there's been a delay because of the whole cppunit vs. catch2 issue. (And catch2 becoming catch 3. ugh! Now I know one of the reasons that @bcarrier has been loath to update the code base...) But I'm getting there. I just don't know if we have libewf in the full tests, and I don't know how to force GitHub to run the checks on a 6 year old PR.

2024-09-07 00:46 UTC, simsong requested changes
Please bring this PR up to the current code base so that the unit tests will run.

2024-09-07 00:54 UTC, bcarrier commented
And looking at this PR a bit more, it is probably an abuse of existing #defines. It's using a v3 function within the #if of v2. So, a full solution would be properly detecting v2 vs v3 and then calling the appropriate method for each.

2024-09-07 02:00 UTC, simsong commented
So should we just kill it?

On Fri, Sep 6, 2024 at 5:55 PM Brian Carrier ***@***.***>
wrote:

> And looking at this PR a bit more, it is probably an abuse of existing
> #defines. It's using a v3 function within the #if of v2. So, a full
> solution would be properly detecting v2 vs v3 and then calling the
> appropriate method for each.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sleuthkit/sleuthkit/pull/1052#issuecomment-2334976922>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAMFHLFIQBC6443EBJ45B5LZVJFGHAVCNFSM6AAAAABNYVPADWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZUHE3TMOJSGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-09-07 13:21 UTC, lfcnassif commented
Just my 2 cents on libewf v3. We upgraded to it because it brings partial Ex01 support and mainly because of this:
https://github.com/sepinf-inc/IPED/issues/993

We have been using it for more than 2 years (20201230 snapshot), thousands of E01 images were processed without issues.

But since it is tagged as experimental, I agree libewf v2 should be still supported.

2024-09-07 13:55 UTC, simsong commented
My personal feeling is that our CI/CD pipeline should test and build with both and actually certify both.

2024-09-07 15:57 UTC, h3xx commented
Original author here. Wow, this PR does not take into consideration the things mentioned in this thread.

- Compatibility with libewf v1 API
- CI testing builds against both v1 and v2

Since this PR is so simple, I'd just as soon close it, especially if this does in fact break compatibility with libewf v1, which it looks like it might. I don't know if it can be improved, only completely re-written.

I'm not usually known for my C. I really only just patch and maintain C projects. That being said, I'm sure someone else more familiar with C could do a better job here and hit the missing points I mentioned above.

Sorry to waste everyone's time with this trivial and none too well-thought-out patch.

2024-09-07 16:00 UTC, simsong commented
Thanks. I will close.

2024-09-07 16:00 UTC, closed without merging