7264 public get hosts
sleuthkit/sleuthkit pull request #2152
Opened 2021-02-05 16:34 UTC by gdicristofaro

2021-02-05 17:14 UTC, rcordovano requested changes

2021-02-05 17:14 UTC, rcordovano commented on bindings/java/src/org/sleuthkit/datamodel/HostManager.java
> +	 * @param status The status to filter on (if null, this will search for
The status will never be null in the case database. Passing null for host status should cause an IllegalArgumentException.

2021-02-05 17:14 UTC, rcordovano commented on bindings/java/src/org/sleuthkit/datamodel/HostManager.java
> +			throw new TskCoreException(String.format("Error getting hosts"), ex);
Please include the host status we are querying for as potential debug info.

2021-02-08 19:46 UTC, APriestman commented on bindings/java/src/org/sleuthkit/datamodel/HostManager.java
> +		String queryString = "SELECT * FROM tsk_hosts WHERE status = ? ";
If we're only going to return active hosts, is there any reason to have the status as a parameter? It doesn't seem like it needs to be a prepared statement either way. Also the top comment block should be changed to indicate that only active hosts will be returned.

2021-02-09 13:42 UTC, APriestman commented on bindings/java/src/org/sleuthkit/datamodel/HostManager.java
> +		try (PreparedStatement s = connection.getPreparedStatement(queryString, Statement.RETURN_GENERATED_KEYS)) {
It looks like this try-with-resources is resulting in the transaction being closed when it shouldn't be.

2021-02-09 14:35 UTC, APriestman approved these changes

2021-02-09 14:45 UTC, merged