4123 Host address manager
sleuthkit/sleuthkit pull request #2172
Opened 2021-02-16 20:20 UTC by APriestman

2021-02-17 16:05 UTC, raman-bt requested changes

2021-02-17 16:14 UTC, APriestman commented on bindings/java/src/org/sleuthkit/datamodel/HostAddressManager.java
> +			preparedStatement.setString(3, address.toLowerCase());
The JIRA specifically said to store the names going into the database as lowercase.

2021-02-17 16:48 UTC, raman-bt approved these changes

2021-02-18 15:28 UTC, raman-bt approved these changes

2021-02-18 15:58 UTC, merged