4160: Log a warning if a thread requests a SQLite connection while it…
sleuthkit/sleuthkit pull request #2194
Opened 2021-02-25 21:24 UTC by raman-bt

… already holds an uncommitted transaction.

2021-02-26 16:58 UTC, rcordovano requested changes

2021-02-26 16:58 UTC, rcordovano commented on bindings/java/src/org/sleuthkit/datamodel/SleuthkitCase.java
> +			}
Can the scope of this synchronized block be reduced to just the call into the Map protected by the lock Object?

2021-03-03 14:59 UTC, raman-bt commented
@rcordovano : I addressed the change you requested.  Could you please take another look and merge it if it looks ok?

2021-03-03 15:39 UTC, rcordovano approved these changes

2021-03-03 15:55 UTC, APriestman approved these changes

2021-03-03 16:37 UTC, merged